// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABey8C5Aj8vCU2CsfDYW-bnFsaVpdbIQI',
    appId: '1:21682642364:web:4df4a9552a002ad0465fb9',
    messagingSenderId: '21682642364',
    projectId: 'emergency-app-flutter',
    authDomain: 'emergency-app-flutter.firebaseapp.com',
    storageBucket: 'emergency-app-flutter.appspot.com',
    measurementId: 'G-HZ9P1RB61V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQH-Bz0iwQ2anhMeU0K3WrovMkDqyZ818',
    appId: '1:21682642364:android:17f4be4d97d77fce465fb9',
    messagingSenderId: '21682642364',
    projectId: 'emergency-app-flutter',
    storageBucket: 'emergency-app-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHY1d0aGqMCwFZwxTp-FrgoW2sr4zBtH4',
    appId: '1:21682642364:ios:51c61cb831aab976465fb9',
    messagingSenderId: '21682642364',
    projectId: 'emergency-app-flutter',
    storageBucket: 'emergency-app-flutter.appspot.com',
    iosClientId: '21682642364-bigmsiv2aj7kng1c5jlsggi68jim75th.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHY1d0aGqMCwFZwxTp-FrgoW2sr4zBtH4',
    appId: '1:21682642364:ios:51c61cb831aab976465fb9',
    messagingSenderId: '21682642364',
    projectId: 'emergency-app-flutter',
    storageBucket: 'emergency-app-flutter.appspot.com',
    iosClientId: '21682642364-bigmsiv2aj7kng1c5jlsggi68jim75th.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathon',
  );
}
